#!/bin/bash
for file in src/components/*.tsx; do
  sed -i 's/text-blue-600/text-primary/g' "$file"
  sed -i 's/text-blue-500/text-primary/g' "$file"
  sed -i 's/text-blue-400/text-primary/g' "$file"
  sed -i 's/text-blue-300/text-primary/g' "$file"
  sed -i 's/text-blue-800/text-primary-hover/g' "$file"
  sed -i 's/bg-blue-600/bg-primary/g' "$file"
  sed -i 's/bg-blue-700/bg-primary-hover/g' "$file"
  sed -i 's/bg-blue-500/bg-primary/g' "$file"
  sed -i 's/bg-blue-50/bg-primary-light/g' "$file"
  sed -i 's/bg-blue-900\/30/bg-primary-light/g' "$file"
  sed -i 's/bg-blue-950\/30/bg-primary-light/g' "$file"
  sed -i 's/bg-blue-950\/10/bg-primary-light/g' "$file"
  sed -i 's/bg-blue-950\/20/bg-primary-light/g' "$file"
  sed -i 's/border-blue-500/border-primary/g' "$file"
  sed -i 's/border-blue-400/border-primary/g' "$file"
  sed -i 's/border-blue-200/border-primary/g' "$file"
  sed -i 's/border-blue-100/border-primary/g' "$file"
  sed -i 's/border-blue-100\/50/border-primary/g' "$file"
  sed -i 's/border-blue-800\/50/border-primary/g' "$file"
  sed -i 's/border-blue-900\/20/border-primary/g' "$file"
  sed -i 's/border-blue-900\/30/border-primary/g' "$file"
  sed -i 's/from-blue-600/from-primary/g' "$file"
  sed -i 's/to-blue-800/to-primary-hover/g' "$file"
done
